#!/usr/bin/env bash

# make user environment match ~/.local/share/chezmoi/user.nix
#
# This will remove any packages you've installed with nix-env
# but have not added to user.nix. To see exactly what this
# will do, run:
#
#     sd nix diff

set -euo pipefail

source $SD/env
nix-env -irf $USER_FILE
