#!/usr/bin/env bash

set -euo pipefail

session_key=""
time="45"
ball="1"

while [[ $# -gt 0 ]]; do
  arg="$1"
  case $arg in
    --key) shift; session_key="$1";;
    --ball) shift; ball="$1";;
    --time) shift; time="$1";;
  esac
  shift
done

check_for_date() {
  month=$1
  day=$2
  out=/tmp/tennis.html
  sd fire curl -s -L -X POST \
    'https://gtc.clubautomation.com/event/reserve-court-new?ajax=true' \
     -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0' \
     --data-raw "reservation-list-page=1&user_id=41668&event_member_token_reserve_court=b86895d3c0bfda3c1871146a5bd1f038&current_guest_count=0&component=2&club=-1&location=1&host=41668&ball_machine=${ball}&date=${month}%2F${day}%2F2023&interval=${time}&time-reserve=&location-reserve=&surface-reserve=&courtsnotavailable=&join-waitlist-case=0" \
     -H "Cookie: PHPSESSID=$session_key;" > $out

  (grep -q "\"times-to-reserve\"" $out \
    || echo " no times available")

  (grep -q "\"court-not-available-text\"" $out \
    || echo "Times available")
}

for i in {1..14}
do
  d=$(date -v +${i}d '+%m %d')
  friendly=$(date -v +${i}d '+%a %m-%d')
  echo -n "$friendly: "
  check_for_date $d
done


