#!/bin/bash

cleanup() {
    rm -f "$tmpfile"
}
trap cleanup  EXIT INT QUIT TERM

# Run older ld (pseudo condition)
profile=default

extract_cookies() {
  sqlfile=$(ls -t "/Users/dave/Library//Application Support/Firefox/Profiles/yw78w5ho.default/cookies.sqlite" | head -1)

  if [ "$sqlfile" != "-" -a ! -r "$sqlfile" ]; then
      echo "Error. File $sqlfile is not readable." >&2
      exit 1
  fi

  # We have to copy cookies.sqlite, because FireFox has a lock on it
  cat "$sqlfile" >> $tmpfile

  # This is the format of the sqlite database:
  # CREATE TABLE moz_cookies (id INTEGER PRIMARY KEY, name TEXT, value TEXT, host TEXT, path TEXT,expiry INTEGER, lastAccessed INTEGER, isSecure INTEGER, isHttpOnly INTEGER);

  echo "# Netscape HTTP Cookie File"
  sqlite3 -separator $'\t' $tmpfile <<- EOF
.mode tabs
.header off
select host,
case substr(host,1,1)='.' when 0 then 'FALSE' else 'TRUE' end,
path,
case isSecure when 0 then 'FALSE' else 'TRUE' end,
expiry,
name,
value
from moz_cookies;
EOF

  cleanup

}

tmpfile="$(mktemp /tmp/cookies.sqlite.XXXXXXXXXX)"
curlcookies="$(mktemp /tmp/curlcookies.XXXXXXXXXX)"

extract_cookies
