#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

profile=default

curlcookies="$(mktemp /tmp/curlcookies.XXXXXXXXXX)"
sd fire cookie "$profile" > "$curlcookies"
curl -b "$curlcookies" "$@" ;
